---
title: "Info"
# special characters for highlighting code : «»
---

``` {.r tab="Console"}
rm(list=ls());                        # clear the Environment tab
options(show.error.locations = TRUE); # show line numbers on error
library(package=ggplot2);             # include all GGPlot2 functions
```

### Issues

#### Lesson fixes

-   Explanation for how to send files

    -   GitHub request 😏🥺 😁

-   Lesson number on title? Match with side?

#### Assets

-   non-breaking spaces??

-   collapse class lesson list

-   mod scripts that have highlighting?

-   \<done\> link to other lessons

-   \<done\> find consistent place to put all GGPlot files

-   \<done\> data files, along with other linked assets, need to be saved in two places (regular folder, docs folder)

    -   this all seems to work now...

-   \<done\> changes between local (main) and github (docs) – best to use URL

-   \<done\> Which module.js gets used?

-   \<done\> Quarto working directory is not the same as R –

    -   causes problem when you want to link to file in R (e.g., weatherData)

#### Lesson module, editor

-   \<done\> codeblockTab in print mode is being edited inline

-   \<done\> print button is gone

-   \<done\> add tab to codeblocks (still needs styling)

-   \<done\> change margin and padding on content

-   \<done\> When a link goes to same page, stop from reloading in website

    -   done for same file – now change in NavBar

-   \<done\> Overflow code lines lost in print mode (code.sourceCode – white-space: pre-wrap)

-   \<done\> more contrast on PDF text?

-   \<done\>Cannot properly add ***figure #:*** to editor when adding figures to plot/code

    -   codeblock – put in div and add single line after (line becomes figure)

-   \<done - hacky \>How do you highlight code in a codeblock in Quarto

    -   Or, use my code styling

-   \<done\> equations

-   \<done\> Firefox print preview breaks in middle of lines (Edge and Chrome are fine)

-   \<done\> CSS does not indicate if a figure has an ID that starts with "fig-"[(why did I want this??)]{.hl}

    -   .fig\[id\^="fig-"\]

#### Quarto editor issues

-   \<done\> fix script links

-   \<done\> images within lists cannot be made into figures

    -   probably just need to hack at Quarto editor and js ignores figures in lists

-   \<done\> do better check on links within a page – make sure you are not capturing links to pages within the website

-   \<done\> horizontally resize viewer (grid -\> body-width: 1000px)

-   \<done\> image change size makes page jump after reload (worse the further you are down the page

    -   does not happen in debug mode (race condition...), only happens in FF

-   \<done\> create module.js for just Quarto

-   \<done\> periods in header titles will mess up highlighting (because the period in JS means something)

-   \<done\> set css to only change object within the Quarto document

-   \<done\> don't jump on link if ref object is on page

-   \<done\>fix last position in shortcut menu

-   \<done\>reduce size of font in document

-   \<done\> figure link open in another window... keep to same

-   \<done – href -\> onclick breaks this!\> less aggressive mouseover on figures

-   \<done\> resize flexsize in editor (this is challenging...)

-   \<done\> figure coloring in editor

-   \<done\> figure reference put number in (Insert -\> Cross Reference)

-   \<done\> highlight line quickly after linking to it

-   \<done\> render changes only for objects within document (not generally)

-   \<done\> render just document with global yml

-   [\<done??\>]{.hl}image resizing does not work when you set height or width in Quarto editor

#### Put in instructions

-   When YAML changes every page needs to be rerendered

-   shortcut to codeblock

-   short to unicode

    -   « »

-   \<put in instructions\> create a newline

    -   one way: \<br\>
    -   another: nbsp (control-space in Visual)
    -   another: \\ in Source

-   copy/paste from D2L causes misalignment of 2nd level bullets -- and the visual editor will treat it as code when switching from Source to Visual

<!-- -->

-   figures under images will not work if there is not blank lines on both sides of the image command in Source

-   figures on codeblocks

-   REnder in a project will Render all open QMD in the yml file

    -   **don't forget to add scripts to the yaml**

### My Infos

-   Editing asset files in the working directory will rerender the files in docs

-   Filenames starting with "\_" and ignored by Quarto (Except for yml)

-   Need to stop Background Jobs before rendering again if you want a webpage to open

-   All file in docs are recreated after rendering

-   If YAML changes, all files need to be rerendered

### Git/GitHub issues

-   creating a new branch inherits everything from current branch

-   git reset HEAD –hard \# tracked files

-   git clean -fd \# untracked files and directories

### Testing Equations and tables here...

$$
\overline{q}_m=\frac{\Delta m}{\Delta t}
$$ {#eq-first}

::: {#fig-eq2}
sadfkhjadkflsa $\overline{q}_m=\frac{\Delta m}{\Delta t}$ fk;sajhdfl
:::

| Col1 |          Col2 |     Col3     | Col4        | Col5    | Col6 |
|------|--------------:|:------------:|-------------|---------|------|
|      |               | sdfgsfdgsdfg | $aselkfhal$ | ertgwer |      |
|      | sdgsdgsdfgfds |              |             | dsgsdg  |      |
|      |               |              |             |         |      |
